FROM gcc

RUN gcc --version

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs

WORKDIR /app

COPY . /app

RUN npm install

CMD ["npm", "run", "test-integration", "--", "zookeeper:2181"]
